version: '3'

networks:
  custom_network:

services:
  app1:
    build:
      context: ./app1
    ports:
      - '4000:4000'
    networks:
      - custom_network

  app2:
    build:
      context: ./app2
    ports:
      - '4001:4001'
    depends_on:
      - app1
    networks:
      - custom_network
